name: LifeAdmin
options:
  bundleIdPrefix: com.lifeadmin
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

targets:
  LifeAdmin:
    type: application
    platform: iOS
    sources:
      - path: LifeAdmin
        excludes:
          - "**/.gitkeep"
      - path: Shared
        excludes:
          - "**/.gitkeep"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lifeadmin.app
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: LifeAdmin
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "LifeAdmin needs microphone access to record voice notes"
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        SWIFT_VERSION: "5.0"
        ENABLE_PREVIEWS: YES
    dependencies:
      - target: LifeAdmin Watch App
        embed: false

  LifeAdmin Watch App:
    type: application
    platform: watchOS
    sources:
      - path: "LifeAdmin Watch App"
        excludes:
          - "**/.gitkeep"
      - path: Shared
        excludes:
          - "**/.gitkeep"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lifeadmin.app.watchkitapp
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: LifeAdmin
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "LifeAdmin needs microphone access to record voice notes"
        INFOPLIST_KEY_WKApplication: YES
        INFOPLIST_KEY_WKCompanionAppBundleIdentifier: com.lifeadmin.app
        INFOPLIST_KEY_WKRunsIndependentlyOfCompanionApp: NO
        INFOPLIST_KEY_WKSupportsActionButton: YES
        SWIFT_VERSION: "5.0"
        ENABLE_PREVIEWS: YES
    entitlements:
      path: "LifeAdmin Watch App/LifeAdmin Watch App.entitlements"
      properties:
        com.apple.developer.watchkit.extended-runtime-session: true

schemes:
  LifeAdmin:
    build:
      targets:
        LifeAdmin: all
        LifeAdmin Watch App: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
